include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - annotate_overrides #
    - await_only_futures #  Future  await
    - avoid_empty_else #  else
    - avoid_js_rounded_ints #  JS
    - avoid_unnecessary_containers #
    - camel_case_extensions #
    - camel_case_types #
    - combinators_ordering #
    - constant_identifier_names #
    - curly_braces_in_flow_control_structures #
    - deprecated_member_use_from_same_package #
    - directives_ordering #
    - empty_constructor_bodies #
    - empty_statements #
    - eol_at_end_of_file #
    - exhaustive_cases #
    - file_names #
    - flutter_style_todos # Flutter
    - implicit_call_tearoffs #  tearoffs
    - join_return_with_assignment #
    - library_names #
    - library_prefixes #
    - library_private_types_in_public_api #  API
    - no_duplicate_case_values #  case
    - non_constant_identifier_names #
    - package_api_docs #  API
    - package_names #
    - prefer_collection_literals #
    - prefer_conditional_assignment #
    - prefer_function_declarations_over_variables #
    - prefer_generic_function_type_aliases #
    - prefer_if_null_operators #  if-null
    - prefer_inlined_adds #
    - prefer_initializing_formals #
    - prefer_is_empty #  isEmpty
    - prefer_relative_imports #
    - prefer_single_quotes #
    - prefer_spread_collections #
    - provide_deprecation_message #
    - slash_for_doc_comments #
    - sized_box_shrink_expand # SizedBox  shrink  expand
    - sort_child_properties_last #
    - sort_constructors_first #
    - sort_pub_dependencies # pub
    - sort_unnamed_constructors_first #
    - strict_top_level_inference #
    - type_annotate_public_apis #  API
    - type_init_formals #
    - use_build_context_synchronously #  BuildContext
    - use_colored_box #
    - use_decorated_box #
    - use_enums #
    - use_function_type_syntax_for_parameters #
    - use_rethrow_when_possible #  rethrow
    - use_super_parameters #  super
    - valid_regexps #
    - unnecessary_async #  async
    - unnecessary_brace_in_string_interps #
    - unnecessary_const #  const
    - unnecessary_constructor_name #
    - unnecessary_getters_setters #  getter  setter
    - unnecessary_lambdas #  lambda
    - unnecessary_string_escapes #
    - unnecessary_string_interpolations #
    - unnecessary_this #  this
    - unnecessary_underscores #

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

bloc:
  rules:
    - prefer_cubit #  Cubit
    - avoid_build_context_extensions #  BuildContext
    - avoid_flutter_imports #  Flutter
    - avoid_public_bloc_methods #  Bloc
    - avoid_public_fields #
    - prefer_file_naming_conventions #
    - prefer_void_public_cubit_methods #  void  Cubit
