
include: package:flutter_lints/flutter.yaml


linter:
  rules:
    # 推荐使用相对导入
    prefer_relative_imports: true
    # 推荐使用指令排序
    directives_ordering: true
    # 推荐使用单引号
    prefer_single_quotes: true
    # 避免不必要的字符串插值
    unnecessary_string_interpolations: true
    # 避免不必要的字符串转义
    unnecessary_string_escapes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

bloc:
  rules:
    prefer_cubit: true # 优先使用 Cubit
    avoid_build_context_extensions: true # 避免使用 BuildContext 扩展
    avoid_flutter_imports: true # 避免使用 Flutter 导入
    avoid_public_bloc_methods: true # 避免使用公共 Bloc 方法
    avoid_public_fields: true # 避免使用公共字段
    prefer_file_naming_conventions: true # 偏好文件命名约定
    prefer_void_public_cubit_methods: true # 偏好 void 公共 Cubit 方法