targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true #  JSON
          any_map: true #
          checked: false #
          include_if_null: false #
          field_rename: none #
