arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: S
nullable-getter: false
use-deferred-loading: false
preferred-supported-locales: ["en"]
use-escaping: false
#
untranslated-messages-file: lib/l10n/untranslated.json
