allprojects {
    repositories {
        google()
        mavenCentral()
        // 添加友盟 Maven 仓库
        maven { url 'https://repo1.maven.org/maven2/' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
