// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLuFzUpINcPQsegupE2QvbYI63Uu0qInE',
    appId: '1:178333310905:android:05b2094296b0ab31e52068',
    messagingSenderId: '178333310905',
    projectId: 'aigun-app-977f0',
    storageBucket: 'aigun-app-977f0.firebasestorage.app',
  );

  // Run 'flutterfire configure' to generate the correct values

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5xoOUGURKlZDXEALsWpY3-m4R2pqwVA',
    appId: '1:178333310905:ios:3e147dc65fa8303fe52068',
    messagingSenderId: '178333310905',
    projectId: 'aigun-app-977f0',
    storageBucket: 'aigun-app-977f0.firebasestorage.app',
    iosBundleId: 'ai.biteagle.aigun',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0MsuK6YKp3s-lzAS9L2aMC_pGgXXX3fs',
    appId: '1:178333310905:web:f17ba6f35257d053e52068',
    messagingSenderId: '178333310905',
    projectId: 'aigun-app-977f0',
    authDomain: 'aigun-app-977f0.firebaseapp.com',
    storageBucket: 'aigun-app-977f0.firebasestorage.app',
    measurementId: 'G-35SMYQGCTZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5xoOUGURKlZDXEALsWpY3-m4R2pqwVA',
    appId: '1:178333310905:ios:b53636a51b3fd76be52068',
    messagingSenderId: '178333310905',
    projectId: 'aigun-app-977f0',
    storageBucket: 'aigun-app-977f0.firebasestorage.app',
    iosBundleId: 'com.aigun.desktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0MsuK6YKp3s-lzAS9L2aMC_pGgXXX3fs',
    appId: '1:178333310905:web:05588efce1404697e52068',
    messagingSenderId: '178333310905',
    projectId: 'aigun-app-977f0',
    authDomain: 'aigun-app-977f0.firebaseapp.com',
    storageBucket: 'aigun-app-977f0.firebasestorage.app',
    measurementId: 'G-E611XWK3JZ',
  );

}