// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UNaZCx-3WHqlpM2QgjT6Usd3xAoi9eI',
    appId: '1:439146808195:android:7b2cdc5ae52d00919facb6',
    messagingSenderId: '439146808195',
    projectId: 'aigun-app',
    storageBucket: 'aigun-app.firebasestorage.app',
  );

  // Run 'flutterfire configure' to generate the correct values

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4RZCjbncmD9HDaoXIBXBVGYtmdx3OzsE',
    appId: '1:439146808195:ios:8aa7a7d2bdf786d49facb6',
    messagingSenderId: '439146808195',
    projectId: 'aigun-app',
    storageBucket: 'aigun-app.firebasestorage.app',
    iosBundleId: 'ai.biteagle.aigun',
  );
}
