name: Staging Environment Build

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      version:
        description: "版本号（例如：1.0.0）"
        required: true
        default: "1.0.0"

jobs:
  build:
    name: Build Staging
    uses: ./.github/workflows/_build-and-release.yml
    with:
      environment: staging
      version: ${{ github.event.inputs.version || '' }}
      dart_define_env: development
      flavor: staging
      enable_obfuscate: false
      s3_prefix: ${{ vars.S3_PREFIX_TEST }}
      release_suffix: -test
      enable_ios_build: false
    secrets: inherit
